#!/usr/bin/env bash

HOUR=$1;
MINUTE=$2;

while true;
do
    MAX_TIME=$(($HOUR * 60 + $MINUTE));
    CURRENT_TIME=$(date | awk '$0 = $4' | awk -F: '$0 = $1 * 60 + $2')
    DIFFERENCE=$(($MAX_TIME - $CURRENT_TIME))
    if [[ $DIFFERENCE > 0 ]]
    then
        echo $DIFFERENCE " minutes left";
        sleep 60
    else
        break;
    fi
done
