#!/usr/bin/env bash

# Default values if absolute time not given
if [ "$#" -eq 0 ];then
    CURRENT_MINUTE=$(date | awk -F'[ :]' '$0=$6');
    HOUR=$(date | awk -F'[ :]' '$0=$5');
    if (( $CURRENT_MINUTE > 30 )); then
        ((HOUR++))
    fi
    MINUTE=30;
else
    HOUR=$1;
    MINUTE=$2;
fi

while true;
do
    MAX_TIME=$(($HOUR * 60 + $MINUTE));
    CURRENT_TIME=$(date | awk '$0 = $4' | awk -F: '$0 = $1 * 60 + $2')
    DIFFERENCE=$(($MAX_TIME - $CURRENT_TIME))
    if [[ $DIFFERENCE > 0 ]]
    then
        clear;
        echo $DIFFERENCE " minutes left";
        sleep 60
    else
        break;
    fi
done
